/**
 * VAANI AI - Local OmniVoice Studio (TTS) Integration Utilities
 * Manages local audio playback and download triggers for reports generated by the backend.
 */

// Local session history logs
let generationHistory = [];

/**
 * Retrieves list of completed generation clips
 * @returns {Array} clips history
 */
export function getGenerationHistory() {
  return generationHistory;
}

/**
 * Resets the session logs list
 */
export function clearGenerationHistory() {
  generationHistory = [];
}

/**
 * Plays an active HTMLAudioElement node
 * @param {HTMLAudioElement} audioElement - Target audio element
 * @returns {Promise} Playback status
 */
export function playAudio(audioElement) {
  if (!audioElement) return Promise.reject(new Error("Audio element not initialized"));
  return audioElement.play();
}

/**
 * Triggers the browser download prompt for synthesized WAV reports
 * @param {string} audioUrl - Target URL of the WAV file
 * @param {string} filename - Download file label
 */
export function downloadAudio(audioUrl, filename = 'report.wav') {
  if (!audioUrl) return;
  const a = document.createElement('a');
  a.href = audioUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
